#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: production database migration rehearsal and additive deployment.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=10

banner "Production database migration"

migration_is_applied() {
  local database_url="$1" migration="$2"
  [[ "$(psql "$database_url" -Atqc "select to_regclass('public._prisma_migrations') is not null")" == "t" ]] || return 1
  [[ "$(psql "$database_url" -Atqc "select exists(select 1 from \"_prisma_migrations\" where migration_name = '$migration' and finished_at is not null and rolled_back_at is null)")" == "t" ]]
}

resolve_if_missing() {
  local database_url="$1" migration="$2"
  if migration_is_applied "$database_url" "$migration"; then
    say "$migration is already recorded as applied."
  else
    DATABASE_URL="$database_url" npx prisma migrate resolve --applied "$migration"
  fi
}

stage "Verify repository and tools"
say "Run this from apps/backend at the exact reviewed release commit."
for tool in node npm npx psql pg_dump pg_restore; do
  command -v "$tool" >/dev/null 2>&1 || { warn "$tool is required"; exit 1; }
done
git diff --quiet && git diff --cached --quiet || { warn "Git worktree is not clean"; exit 1; }
step "Install exactly package-lock.json (Prisma 6.12.0)."
confirm "Run npm ci now?" && npm ci
[[ "$(node -p "require('prisma/package.json').version")" == "6.12.0" ]] || {
  warn "Installed Prisma is not 6.12.0"; exit 1;
}
say "Toolchain is pinned to Prisma 6.12.0."
pause

stage "Identify production safely"
ask_secret PROD_DATABASE_URL "Paste the production PostgreSQL DATABASE_URL (not saved):"
ask PROD_DATABASE_NAME "Type the expected production database name:"
ACTUAL_DATABASE_NAME=$(psql "$PROD_DATABASE_URL" -Atqc 'select current_database()')
[[ "$ACTUAL_DATABASE_NAME" == "$PROD_DATABASE_NAME" ]] || {
  warn "Connected to $ACTUAL_DATABASE_NAME, expected $PROD_DATABASE_NAME"; exit 1;
}
[[ ! "$ACTUAL_DATABASE_NAME" =~ [Tt][Ee][Ss][Tt] ]] || {
  warn "Production database name unexpectedly contains test"; exit 1;
}
say "Connected database identity confirmed: $ACTUAL_DATABASE_NAME"
pause

stage "Freeze writes"
warn "This wizard cannot know how your process manager stops application writes."
step "Enable maintenance mode or stop every API/worker instance that writes this database."
step "Confirm active scanners have finished their current request."
confirm "Are all application writes stopped?" || exit 1

stage "Create and verify backup"
ask BACKUP_DIRECTORY "Absolute directory for the production backup:"
[[ "$BACKUP_DIRECTORY" == /* ]] || { warn "Backup directory must be absolute"; exit 1; }
mkdir -p "$BACKUP_DIRECTORY"
BACKUP_FILE="$BACKUP_DIRECTORY/${PROD_DATABASE_NAME}_before_normalization_$(date +%Y%m%d_%H%M%S).dump"
say "Creating PostgreSQL custom-format backup at $BACKUP_FILE"
pg_dump --format=custom --file="$BACKUP_FILE" "$PROD_DATABASE_URL"
pg_restore --list "$BACKUP_FILE" >/dev/null
[[ -s "$BACKUP_FILE" ]] || { warn "Backup is empty"; exit 1; }
say "Backup archive is readable. Keep it outside this server as well."
pause

stage "Restore rehearsal copy"
ask_secret REHEARSAL_DATABASE_URL "Paste an EMPTY rehearsal DATABASE_URL whose database name contains test (not saved):"
REHEARSAL_DATABASE_NAME=$(psql "$REHEARSAL_DATABASE_URL" -Atqc 'select current_database()')
[[ "$REHEARSAL_DATABASE_NAME" =~ [Tt][Ee][Ss][Tt] ]] || {
  warn "Rehearsal database name must contain test"; exit 1;
}
warn "The next operation replaces all data inside $REHEARSAL_DATABASE_NAME only."
confirm "Restore the verified production backup into this test database?" || exit 1
pg_restore --clean --if-exists --no-owner --dbname="$REHEARSAL_DATABASE_URL" "$BACKUP_FILE"
say "Production backup restored to $REHEARSAL_DATABASE_NAME."
pause

stage "Capture migration evidence"
say "No migration is applied in this stage. Save this output for review."
DATABASE_URL="$REHEARSAL_DATABASE_URL" npx prisma migrate status || true
psql "$REHEARSAL_DATABASE_URL" -c '\dt'
psql "$REHEARSAL_DATABASE_URL" -c '\dv'
step "Compare the schema with migrations 0 through 20260908110000."
warn "Do not mark a migration applied merely because its name looks familiar."
pause "Press Enter only after a DBA confirms the exact existing migration prefix."

stage "Baseline rehearsal history"
say "For the repository's documented pre-redesign schema, the expected existing prefix is the first five migrations."
warn "Use this only if the previous stage proved that exact schema equivalence."
confirm "Did the DBA verify production already matches migrations through 20260908110000?" || exit 1
for migration in \
  0_legacy_baseline \
  20260906120000_category_specific_scan_tables \
  20260907130000_ac_pcb_odu \
  20260907150000_recordscan_all_legacy \
  20260908110000_drop_legacy_scan_storage; do
  resolve_if_missing "$REHEARSAL_DATABASE_URL" "$migration"
done
DATABASE_URL="$REHEARSAL_DATABASE_URL" npx prisma migrate status
pause

stage "Rehearse additive migration"
confirm "Apply pending additive migrations to the rehearsal database?" || exit 1
DATABASE_URL="$REHEARSAL_DATABASE_URL" npx prisma migrate deploy
set +e
DATABASE_URL="$REHEARSAL_DATABASE_URL" ALLOW_READ_ONLY_PRODUCTION_PREFLIGHT="" npm run db:preflight
PREFLIGHT_STATUS=$?
set -e
[[ "$PREFLIGHT_STATUS" -ne 1 ]] || { warn "Preflight could not run."; exit 1; }
if [[ "$PREFLIGHT_STATUS" -eq 2 ]]; then
  warn "Preflight found source-data blockers. Additive schema deployment may proceed, but backfill may not."
  confirm "Has the DBA reviewed and accepted this preflight report for additive-only deployment?" || exit 1
fi
say "Do not run Phase 3/4 against production; their production write path is intentionally disabled."
pause

stage "Apply additive production migration"
warn "This changes production schema. The backup and successful rehearsal are mandatory."
confirm "Did rehearsal pass and has the DBA approved this exact release?" || exit 1
for migration in \
  0_legacy_baseline \
  20260906120000_category_specific_scan_tables \
  20260907130000_ac_pcb_odu \
  20260907150000_recordscan_all_legacy \
  20260908110000_drop_legacy_scan_storage; do
  resolve_if_missing "$PROD_DATABASE_URL" "$migration"
done
confirm "Type y to deploy only the remaining additive migration now?" || exit 1
DATABASE_URL="$PROD_DATABASE_URL" npx prisma migrate deploy

stage "Verify and resume"
DATABASE_URL="$PROD_DATABASE_URL" npx prisma migrate status
psql "$PROD_DATABASE_URL" -v ON_ERROR_STOP=1 -c \
  "select to_regclass('public.production_units') as production_units, to_regclass('public.recordscan') as normalized_recordscan, to_regclass('public.migration_quarantine') as migration_quarantine;"
step "Start one application instance and perform read-only health checks."
step "Then resume all instances and monitor errors before accepting new scans."
warn "Keep $BACKUP_FILE and do not run contract/drop migrations."
confirm "Have health checks passed and application writes resumed?" || exit 1

finish
